"""initial schema

Revision ID: ec9230cc677a
Revises: 
Create Date: 2026-02-26 02:01:01.272968
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ec9230cc677a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('source_channel', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('photos_count', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    op.create_index('idx_businesses_category', 'businesses', ['category'], unique=False)
    op.create_index('idx_businesses_city', 'businesses', ['city'], unique=False)
    op.create_index('idx_businesses_place_id', 'businesses', ['place_id'], unique=False)
    op.create_table('search_configs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('niche', sa.String(length=255), nullable=False),
    sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('radius_miles', sa.Integer(), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrichment_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('best_email', sa.String(length=255), nullable=True),
    sa.Column('all_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_position', sa.String(length=255), nullable=True),
    sa.Column('social_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enrichment_source', sa.String(length=50), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('lead_lifecycle',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_lead_scores_range'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('outreach_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=True),
    sa.Column('llc_filing_id', sa.BigInteger(), nullable=True),
    sa.Column('source_channel', sa.String(length=20), nullable=False),
    sa.Column('outreach_type', sa.String(length=20), nullable=False),
    sa.Column('email_sent_to', sa.String(length=255), nullable=True),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('redirect_url', sa.Text(), nullable=True),
    sa.Column('is_free_subdomain', sa.Boolean(), nullable=False),
    sa.Column('triaged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('website_audits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('url_audited', sa.Text(), nullable=False),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('best_practices_score', sa.Integer(), nullable=True),
    sa.Column('lcp_seconds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fid_ms', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cls_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('fcp_seconds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('speed_index_seconds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_blocking_ms', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('has_ssl', sa.Boolean(), nullable=True),
    sa.Column('ssl_valid', sa.Boolean(), nullable=True),
    sa.Column('ssl_expires', sa.DateTime(), nullable=True),
    sa.Column('is_mobile_friendly', sa.Boolean(), nullable=True),
    sa.Column('has_viewport_meta', sa.Boolean(), nullable=True),
    sa.Column('has_horizontal_scroll', sa.Boolean(), nullable=True),
    sa.Column('small_tap_targets', sa.Integer(), nullable=True),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_page_builder', sa.Boolean(), nullable=True),
    sa.Column('is_wordpress', sa.Boolean(), nullable=True),
    sa.Column('copyright_year', sa.Integer(), nullable=True),
    sa.Column('is_outdated', sa.Boolean(), nullable=True),
    sa.Column('raw_lighthouse', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_audits')
    op.drop_table('triage_results')
    op.drop_table('outreach_log')
    op.drop_table('lead_scores')
    op.drop_table('lead_lifecycle')
    op.drop_table('enrichment_data')
    op.drop_table('search_configs')
    op.drop_index('idx_businesses_place_id', table_name='businesses')
    op.drop_index('idx_businesses_city', table_name='businesses')
    op.drop_index('idx_businesses_category', table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
